site_name: Programming Contest Hosting Guide

theme: readthedocs

nav:
  - 메인 : index.md
  - 대회 준비 :
    - 대회 기반 준비 : preparation.md
    - 대회 문제 세팅 및 검수 : problem_setting.md
    
  - 대회 중 :
    - 대회 현장 : during_contest.md
  
  - 대회 종료 :
    - 대회 종료 : contest_end.md
    
  - 업데이트 내역 :
    - 업데이트 내역 : updatelog.md
    
  - 도움 주신 분들 :
    - 도움 주신 분들 : credits.md

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
extra:
  version:
    v 0a.009