site_name: Programming Contest Hosting Guide (v 0a.000)

theme: readthedocs

nav:
  - 메인 : index.md
  - 대회 준비 :
    - 대회 기반 준비 : preparation.md
    - 대회 문제 세팅 및 검수 : problem_setting.md
    
  - 대회 중 :
    - 대회 현장 : during_contest.md
  
  - 대회 종료 :
    - 대회 종료 : contest_end.md

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js